# Update subscription links
name: Daily Update

on:
  # Runs at 08:00 UTC every day
  schedule:
    - cron: '0 8 * * *'

  # Manual updates
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - name: Update Links
        # Condition to prevent unintended automatic workflow
        # Change or comment out this line for automatic workflow on forks
        if: github.repository == 'williamstar007/clashx-v2ray-topfreeproxy'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          python .github/workflows/update.py
          git add  README.md v2ray.md clash中文版.md v2ray中文版.md
          git commit -m "updates"
          git push
          
